//
// Generated file, do not edit! Created by nedtool 5.6 from test.msg.
//

#ifndef __TEST_M_H
#define __TEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>test.msg:2</tt> by nedtool.
 * <pre>
 * message TestMsg
 * {
 *     int id;	//节点标号
 *     double distance; //到sink的距离
 *     int hopCount = 0; //到sink的跳数
 * }
 * </pre>
 */
class TestMsg : public ::omnetpp::cMessage
{
  protected:
    int id;
    double distance;
    int hopCount;

  private:
    void copy(const TestMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TestMsg&);

  public:
    TestMsg(const char *name=nullptr, short kind=0);
    TestMsg(const TestMsg& other);
    virtual ~TestMsg();
    TestMsg& operator=(const TestMsg& other);
    virtual TestMsg *dup() const override {return new TestMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual double getDistance() const;
    virtual void setDistance(double distance);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TestMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TestMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TEST_M_H

